let wordsContainer = document.getElementById("word-item");
let inputText = document.getElementById("inputtext");
let wordID = 1;
let wordsSubmitted = 0;
let correctWord = 0;
let flag = 0;
let seconds;
let timing = 30;
//select 40 words to display from array
function wordsToDisplay() {
  var basicWords = [
    "a",
    "about",
    "above",
    "across",
    "act",
    "add",
    "afraid",
    "after",
    "again",
    "age",
    "ago",
    "agree",
    "air",
    "all",
    "alone",
    "along",
    "always",
    "am",
    "amount",
    "an",
    "and",
    "angry",
    "another",
    "answer",
    "any",
    "anyone",
    "appear",
    "apple",
    "are",
    "area",
    "arm",
    "army",
    "around",
    "arrive",
    "art",
    "as",
    "ask",
    "at",
    "aunt",
    "away",
    "baby",
    "back",
    "bad",
    "bag",
    "ball",
    "bank",
    "base",
    "bath",
    "be",
    "bean",
    "bear",
    "bed",
    "beer",
    "before",
    "begin",
    "bell",
    "below",
    "best",
    "big",
    "bird",
    "birth",
    "bit",
    "bite",
    "black",
    "bleed",
    "block",
    "blood",
    "blow",
    "blue",
    "board",
    "boat",
    "body",
    "boil",
    "bone",
    "book",
    "border",
    "born",
    "both",
    "bowl",
    "box",
    "boy",
    "branch",
    "brave",
    "bread",
    "break",
    "breathe",
    "bridge",
    "bright",
    "bring",
    "brother",
    "brown",
    "brush",
    "build",
    "burn",
    "bus",
    "busy",
    "but",
    "buy",
    "by",
    "cake",
    "call",
    "can",
    "cap",
    "car",
    "card",
    "care",
    "carry",
    "case",
    "cat",
    "catch",
    "chair",
    "chase",
    "cheap",
    "cheese",
    "child",
    "choice",
    "circle",
    "city",
    "class",
    "clever",
    "clean",
    "clear",
    "climb",
    "clock",
    "cloth",
    "cloud",
    "close",
    "coffee",
    "coat",
    "coin",
    "cold",
    "colour",
    "comb",
    "common",
    "compare",
    "come",
    "control",
    "cook",
    "cool",
    "copper",
    "corn",
    "corner",
    "correct",
    "cost",
    "count",
    "cover",
    "crash",
    "cross",
    "cry",
    "cup",
    "cut",
    "dance",
    "dark",
    "day",
    "dead",
    "decide",
    "deep",
    "deer",
    "desk",
    "die",
    "dirty",
    "dish",
    "do",
    "dog",
    "door",
    "down",
    "draw",
    "dream",
    "dress",
    "drink",
    "drive",
    "drop",
    "dry",
    "duck",
    "dust",
    "duty",
    "each",
    "ear",
    "early",
    "earn",
    "earth",
    "east",
    "easy",
    "eat",
    "effect",
    "egg",
    "eight",
    "else",
    "empty",
    "end",
    "enemy",
    "enjoy",
    "enter",
    "equal",
    "even",
    "event",
    "ever",
    "every",
    "exact",
    "except",
    "expect",
    "explain",
    "eye",
    "face",
    "fact",
    "fail",
    "fall",
    "false",
    "family",
    "famous",
    "far",
    "farm",
    "fast",
    "fat",
    "fault",
    "fear",
    "feed",
    "feel",
    "fever",
    "few",
    "fight",
    "fill",
    "film",
    "find",
    "fine",
    "fire",
    "first",
    "fish",
    "fit",
    "five",
    "fix",
    "flag",
    "flat",
    "float",
    "floor",
    "flour",
    "fly",
    "fold",
    "food",
    "fool",
    "foot",
    "for",
    "force",
    "forest",
    "forget",
    "fork",
    "form",
    "fox",
    "four",
    "free",
    "freeze",
    "fresh",
    "friend",
    "from",
    "front",
    "fruit",
    "full",
    "fun",
    "funny",
    "future",
    "game",
    "gate",
    "get",
    "gift",
    "give",
    "glad",
    "glass",
    "go",
    "goat",
    "god",
    "gold",
    "good",
    "grass",
    "grave",
    "great",
    "green",
    "gray",
    "group",
    "grow",
    "gun",
    "hair",
    "half",
    "hall",
    "hand",
    "happy",
    "hard",
    "hat",
    "hate",
    "have",
    "he",
    "head",
    "hear",
    "heavy",
    "heart",
    "hello",
    "help",
    "hen",
    "her",
    "here",
    "hers",
    "hide",
    "high",
    "hill",
    "him",
    "his",
    "hit",
    "hobby",
    "hold",
    "hole",
    "home",
    "hope",
    "horse",
    "hot",
    "hotel",
    "house",
    "how",
    "hour",
    "hurry",
    "hurt",
    "I",
    "ice",
    "idea",
    "if",
    "in",
    "into",
    "invent",
    "iron",
    "is",
    "island",
    "it",
    "its",
    "jelly",
    "job",
    "join",
    "juice",
    "jump",
    "just",
    "keep",
    "key",
    "kill",
    "kind",
    "king",
    "knee",
    "knife",
    "knock",
    "know",
    "lady",
    "lamp",
    "land",
    "large",
    "last",
    "late",
    "laugh",
    "lazy",
    "lead",
    "leaf",
    "learn",
    "leave",
    "leg",
    "left",
    "lend",
    "length",
    "less",
    "lesson",
    "let",
    "letter",
    "lie",
    "life",
    "light",
    "like",
    "lion",
    "lip",
    "list",
    "live",
    "lock",
    "lonely",
    "long",
    "look",
    "lose",
    "lot",
    "love",
    "low",
    "lower",
    "luck",
    "main",
    "make",
    "male",
    "man",
    "many",
    "map",
    "mark",
    "may",
    "me",
    "meal",
    "mean",
    "meat",
    "meet",
    "milk",
    "mind",
    "miss",
    "mix",
    "model",
    "money",
    "month",
    "moon",
    "more",
    "most",
    "mouth",
    "move",
    "much",
    "music",
    "must",
    "my",
    "name",
    "near",
    "neck",
    "need",
    "needle",
    "net",
    "never",
    "new",
    "news",
    "next",
    "nice",
    "night",
    "nine",
    "no",
    "noble",
    "noise",
    "none",
    "nor",
    "north",
    "nose",
    "not",
    "notice",
    "now",
    "obey",
    "ocean",
    "of",
    "off",
    "offer",
    "office",
    "often",
    "oil",
    "old",
    "on",
    "one",
    "only",
    "open",
    "or",
    "orange",
    "order",
    "other",
    "our",
    "out",
    "over",
    "own",
    "page",
    "pain",
    "paint",
    "pair",
    "pan",
    "paper",
    "park",
    "part",
    "party",
    "pass",
    "past",
    "path",
    "pay",
    "peace",
    "pen",
    "per",
    "piano",
    "pick",
    "piece",
    "pig",
    "pin",
    "pink",
    "place",
    "plane",
    "plant",
    "plate",
    "play",
    "please",
    "plenty",
    "point",
    "polite",
    "pool",
    "poor",
    "pour",
    "power",
    "press",
    "pretty",
    "price",
    "prince",
    "prison",
    "prize",
    "pull",
    "punish",
    "pupil",
    "push",
    "put",
    "queen",
    "quick",
    "quiet",
    "radio",
    "rain",
    "rainy",
    "raise",
    "reach",
    "read",
    "ready",
    "real",
    "red",
    "rent",
    "reply",
    "rest",
    "rice",
    "rich",
    "ride",
    "right",
    "ring",
    "rise",
    "road",
    "rob",
    "rock",
    "room",
    "round",
    "rude",
    "rule",
    "ruler",
    "run",
    "rush",
    "sad",
    "safe",
    "sail",
    "salt",
    "same",
    "sand",
    "save",
    "say",
    "school",
    "search",
    "seat",
    "second",
    "see",
    "seem",
    "sell",
    "send",
    "serve",
    "seven",
    "sex",
    "shade",
    "shake",
    "shape",
    "share",
    "sharp",
    "she",
    "sheep",
    "sheet",
    "shine",
    "ship",
    "shirt",
    "shoe",
    "shoot",
    "shop",
    "short",
    "shout",
    "show",
    "sick",
    "side",
    "silly",
    "silver",
    "simple",
    "single",
    "since",
    "sing",
    "sink",
    "sister",
    "sit",
    "six",
    "size",
    "skill",
    "skin",
    "skirt",
    "sky",
    "sleep",
    "slip",
    "slow",
    "small",
    "smell",
    "smile",
    "smoke",
    "snow",
    "so",
    "soap",
    "sock",
    "soft",
    "some",
    "son",
    "soon",
    "sorry",
    "sound",
    "soup",
    "south",
    "space",
    "speak",
    "speed",
    "spell",
    "spend",
    "spoon",
    "sport",
    "spread",
    "spring",
    "square",
    "stamp",
    "stand",
    "star",
    "start",
    "stay",
    "steal",
    "steam",
    "step",
    "still",
    "stone",
    "stop",
    "store",
    "storm",
    "story",
    "street",
    "study",
    "stupid",
    "such",
    "sugar",
    "sun",
    "sunny",
    "sure",
    "sweet",
    "swim",
    "sword",
    "table",
    "take",
    "talk",
    "tall",
    "taste",
    "taxi",
    "tea",
    "teach",
    "team",
    "tear",
    "tell",
    "ten",
    "tennis",
    "test",
    "than",
    "that",
    "the",
    "their",
    "then",
    "there",
    "these",
    "thick",
    "thin",
    "thing",
    "think",
    "third",
    "this",
    "threat",
    "three",
    "tidy",
    "tie",
    "title",
    "to",
    "today",
    "toe",
    "too",
    "tool",
    "tooth",
    "top",
    "total",
    "touch",
    "town",
    "train",
    "tram",
    "tree",
    "true",
    "trust",
    "twice",
    "try",
    "turn",
    "type",
    "ugly",
    "uncle",
    "under",
    "unit",
    "until",
    "up",
    "use",
    "useful",
    "usual",
    "usually",
    "very",
    "voice",
    "visit",
    "wait",
    "wake",
    "walk",
    "want",
    "warm",
    "was",
    "wash",
    "waste",
    "watch",
    "water",
    "way",
    "we",
    "weak",
    "wear",
    "week",
    "weight",
    "were",
    "well",
    "west",
    "wet",
    "what",
    "wheel",
    "when",
    "where",
    "which",
    "while",
    "white",
    "who",
    "why",
    "wide",
    "wife",
    "wild",
    "will",
    "win",
    "wind",
    "wine",
    "wire",
    "wise",
    "wish",
    "with",
    "woman",
    "word",
    "work",
    "world",
    "worry",
    "yard",
    "yell",
    "yet",
    "you",
    "young",
    "your",
    "zero",
    "zoo",
  ];
  let wordsToDisplay = [];
  for (let i = 0; i < 40; i++) {
    let Number = Math.floor(Math.random() * basicWords.length);
    //console.log(Number)
    // console.log(basicWords[Number])
    wordsToDisplay.push(basicWords[Number] + " ");
  }
  return wordsToDisplay;
}

//  console.log(topWords[Number])
//   console.log(randomNumber)

// let promise = fetch("https://random-word-api.herokuapp.com/word?number=50");
// promise.then((response)=>{
//     return response.json();
// }).then((data)=>{
//     console.log(data)
// })

//display words
function displayWords() {
  wordID = 1;
  wordsContainer.innerHTML = "";
  let newTest = wordsToDisplay();
  console.log(newTest);

  newTest.forEach((word, index) => {
    let wordSpan = document.createElement("span");
    wordSpan.innerText = word;
    wordSpan.setAttribute("id", "word " + (index + 1));
    wordsContainer.appendChild(wordSpan);
  });
}
displayWords();
inputText.addEventListener("input", function (e) {
  if (flag === 0) {
    flag = 1;
    timeStart();
  }

  currentWord();
  // console.log("e.data function "+ e.data)
  if (e.data === " ") {
    checkWord();
  }
});
function checkWord() {
  const wordEntered = inputText.value;
  let enteredWordID = "word " + wordID;
  //console.log(enteredWordID);
  wordID++;
  wordsSubmitted++;
  inputText.value = "";
  let checkOriginalWord = document.getElementById(enteredWordID);
  if (checkOriginalWord.innerText === wordEntered) {
    correctWord++;
    cw.innerText = correctWord;
    console.log(correctWord);
    console.log(wordsSubmitted);
    spanColor(enteredWordID, 1);
  } else {
    spanColor(enteredWordID, 2);
  }
}
function spanColor(enteredWordID, colorID) {
  let spanToBeColored = document.getElementById(enteredWordID);

  if (colorID === 1) {
    spanToBeColored.classList.remove("current");
    spanToBeColored.classList.add("correct");
  } else if (colorID === 2) {
    spanToBeColored.classList.remove("current");
    spanToBeColored.classList.add("wrong");
  } else if (colorID === 3) {
    spanToBeColored.classList.add("current");
  }
}
function currentWord() {
  const wordEntered = inputText.value;
  let enteredWordID = "word " + wordID;
  spanColor(enteredWordID, 3);
}
function timeStart() {
  seconds = setInterval(function () {
    time.innerText--;
    console.log("time" + time.innerText);
    if (time.innerText == "-1") {
      timeOver();
      clearInterval(seconds);
    }
  }, 1000);
}
function timeOver() {
  inputText.value = '';
  inputText.disabled = true;
  restartbtn.focus();

  displayScore();
}
function displayScore() {
  let percentage = 0;
  if (wordsSubmitted != 0) {
    percentage = Math.floor((correctWord / wordsSubmitted) * 100);
  }

  time.innerText = percentage + " %";
  timename.innerText = "PA ";
  cwName.innerText = "WPM";
  cw.innerText = 2 * correctWord;
}
restartbtn.addEventListener("click", function () {
  wordsSubmitted = 0;
  correctWord = 0;
  flag = 0;
  time.innerText = timing;
  timename.innerText = "Timer";
  cw.innerText = correctWord;
  cwName.innerText = "CW";
  inputText.disabled = false;
  inputText.value = "";
  inputText.focus();
  clearInterval(seconds);
  displayWords();
});
